version: "3"
volumes:
  mongodata:
services:
  python:
    build:
      context: .
      dockerfile: docker/prod/python/Dockerfile
    environment:
      HOST_NAME: https://short.vadi.tel/
      MONGO_HOST: mongodb://mongodb
      MONGO_PORT: 27017
      MONGO_DATABASE_NAME: url_shortener
    volumes:
      - ./app:/usr/src/app
    ports:
      - 8000:8000
  mongodb:
    image: mongo:3.6.18
    environment:
      MONGO_HOST: mongodb://localhost
      MONGO_PORT: 27017
      MONGO_DATABASE_NAME: url_shortener
    volumes:
      - mongodata:/var/lib/mongodb/data
    ports:
      - 27017:27017